# Vineland-3 Comprehensive Interview Form Items
# English items from official Pearson sample report
# Arabic items translated from Vineland-3 using Arafa Vineland-II Arabic version
# as style/tone reference — same language register and clinical phrasing

# ═══════════════════════════════════════════════════════════
# ENGLISH ITEMS
# ═══════════════════════════════════════════════════════════
ITEMS_EN = {
    "rec": {
        "1": "Responds to parent/caregiver's voice by looking.",
        "2": "Looks when parent/caregiver gestures for attention.",
        "3": "Responds upon hearing his/her name called.",
        "4": "Follows parent/caregiver/teacher's gaze or pointing.",
        "5": "Understands at least 10 words.",
        "6": "Understands at least three basic gestures.",
        "7": "Understands the word 'no'.",
        "8": "Understands at least three facial expressions.",
        "9": "Understands the word 'yes'.",
        "10": "Follows instructions requiring only one action.",
        "11": "Identifies at least three actual objects.",
        "12": "Understands at least 50 words.",
        "13": "Responds to the tone of spoken words.",
        "14": "Identifies at least three body parts on self.",
        "15": "Follows instructions with one action and one object.",
        "16": "Understands at least three more advanced gestures.",
        "17": "Identifies at least three pictured objects.",
        "18": "Identifies at least three pictured body parts.",
        "19": "Responds to questions that use the word 'what'.",
        "20": "Responds to questions that use the word 'who'.",
        "21": "Identifies at least three pictured actions.",
        "22": "Responds to questions that use the word 'where'.",
        "23": "Follows instructions with two related actions.",
        "24": "Follows instructions with one action and two objects.",
        "25": "Follows 'if-then' instructions.",
        "26": "Pays attention to a story for at least 15 minutes.",
        "27": "Responds to questions that use the word 'why'.",
        "28": "Follows instructions with two unrelated actions.",
        "29": "Responds to questions that use the word 'when'.",
        "30": "Pays attention to a show for at least 30 minutes.",
        "31": "Identifies left and right on his/her own body.",
        "32": "Follows instructions requiring three actions.",
        "33": "Pays attention to a show for at least 60 minutes.",
        "34": "Understands sarcasm.",
        "35": "Pays attention to a 15-minute informational talk.",
        "36": "Follows instructions involving right and left.",
        "37": "Remembers to do something up to an hour later.",
        "38": "Remembers to do something several hours later.",
        "39": "Pays attention to a 30-minute informational talk.",
    },
    "exp": {
        "1": "Makes sounds of pleasure.",
        "2": "Cries or fusses when uncomfortable.",
        "3": "Vocalizes or gestures to get attention.",
        "4": "Makes at least three one-syllable speech sounds.",
        "5": "Babbles in strings of sounds.",
        "6": "Vocalizes or gestures to continue or stop an activity.",
        "7": "Says Dada, Mama, or other parent/caregiver name.",
        "8": "Uses at least three basic gestures.",
        "9": "Repeats or tries to repeat common words.",
        "10": "Says 'no'.",
        "11": "Names at least three objects.",
        "12": "Says one-word requests.",
        "13": "Names at least 10 objects.",
        "14": "Says 'yes'.",
        "15": "Names at least three actions.",
        "16": "Calls siblings, peers, etc. by their name or nickname.",
        "17": "Says at least 50 words.",
        "18": "Uses phrases with a noun and a verb.",
        "19": "Says his/her own first name or nickname.",
        "20": "Uses pronouns to refer to self.",
        "21": "Uses simple adjectives to describe things.",
        "22": "Says what he/she is doing using simple sentences.",
        "23": "Uses at least three more advanced gestures.",
        "24": "Uses negatives in sentences.",
        "25": "Says his/her age when asked.",
        "26": "Uses possessives in phrases or sentences.",
        "27": "Uses the word 'and' in phrases or sentences.",
        "28": "Asks questions using the word 'who'.",
        "29": "Uses plural nouns.",
        "30": "Uses pronouns to refer to others.",
        "31": "Uses the words 'in', 'on', and 'under'.",
        "32": "Asks questions using the word 'why'.",
        "33": "Says both his/her first and last name when asked.",
        "34": "Uses pronouns correctly.",
        "35": "Asks questions using the word 'when'.",
        "36": "Uses the word 'because' in phrases or sentences.",
        "37": "Says age at his/her next birthday when asked.",
        "38": "Uses past tense verbs.",
        "39": "Tells the basic parts of a familiar story or plot.",
        "40": "Uses 'behind', 'in front of', and 'between'.",
        "41": "Gives simple directions involving one or two steps.",
        "42": "Uses compound sentences joined by 'and' or 'but'.",
        "43": "Uses own knowledge or opinions to comment.",
        "44": "Tells about everyday experiences in detail.",
        "45": "Tells about one-time experiences in detail.",
        "46": "Says both the month and day of his/her birthday.",
        "47": "Clarifies by restating differently when needed.",
        "48": "Says his/her complete home address correctly.",
        "49": "Gives complex directions with three or more steps.",
    },
    "wrn": {
        "1": "Holds a book and turns pages correctly for reading.",
        "2": "Recognizes one or more simple signs/icons/symbols.",
        "3": "Identifies one or more alphabet letters.",
        "4": "Recognizes his/her own name in printed form.",
        "5": "Identifies at least 10 alphabet letters.",
        "6": "Understands how his/her language is written.",
        "7": "Writes in the correct direction for his/her language.",
        "8": "Copies his/her own first name correctly.",
        "9": "Copies simple words from an example correctly.",
        "10": "Identifies all alphabet letters, upper- and lowercase.",
        "11": "Writes alphabet letters using correct orientation.",
        "12": "Reads at least 10 words.",
        "13": "Writes both his/her first and last name from memory.",
        "14": "Reads sentences of three or more words out loud.",
        "15": "Copies phrases of four or more words correctly.",
        "16": "Writes at least 10 simple words from memory.",
        "17": "Reads simple stories out loud.",
        "18": "Writes simple sentences of three or more words.",
        "19": "Writes at least 20 words from memory.",
        "20": "Reads at a second-grade level or higher.",
        "21": "Writes simple correspondence of three sentences.",
        "22": "Follows along while reading a story.",
        "23": "Reads and understands simple paragraphs.",
        "24": "Writes a paragraph of five sentences or more.",
        "25": "Reads books at a fourth-grade level or higher.",
        "26": "Writes in a connected manner most of the time.",
        "27": "Reads books for pleasure.",
        "28": "Writes topics at a basic first-grade level.",
        "29": "Reads newspapers at an adult level.",
        "30": "Writes letters about work.",
        "31": "Uses a dictionary.",
        "32": "Uses the index in books.",
        "33": "Writes composition topics.",
        "34": "Writes the address on envelopes.",
        "35": "Uses word lists from books.",
        "36": "Reads stories in newspapers or weekly magazines.",
        "37": "Writes all letters of the alphabet from memory.",
        "38": "Reads at least three words out loud.",
        "39": "States his/her birth date by day and month when asked.",
        "40": "Uses plural and singular forms.",
        "41": "Writes first and last name.",
        "42": "States home telephone number when asked.",
        "43": "Can give full address including city and district when asked.",
        "44": "Reads at least 10 words out loud.",
        "45": "Writes at least 10 words from memory.",
        "46": "Expresses ideas in more than one way without help.",
        "47": "Reads a simple story aloud.",
        "48": "Writes a simple sentence of three or four words.",
        "49": "Follows a general event in a school or related setting for more than 15 minutes.",
        "50": "Reads on his/her own.",
        "51": "Reads books to at least a second-grade primary level.",
        "52": "Arranges words alphabetically by first letter.",
        "53": "Writes short letters or messages.",
        "54": "Describes places to others that require traveling in multiple directions.",
        "55": "Writes simple topics at a basic first-grade level.",
        "56": "Reads books to at least a fourth-grade primary level.",
        "57": "Writes words in a connected and consistent manner most of the time.",
        "58": "Uses a dictionary.",
        "59": "Uses indexes in books he/she reads.",
        "60": "Writes composition topics.",
        "61": "Writes the address on envelope fronts.",
        "62": "Uses word lists from books.",
        "63": "Reads stories for adults in newspapers.",
        "64": "Has long-term goals and describes plans to achieve them.",
        "65": "Reads adult magazines or weekly story magazines.",
        "66": "Writes letters about work.",
    },
    "per": {
        "1": "Opens his/her mouth when food is offered.",
        "2": "Drinks from a bottle or spill-proof drinking cup.",
        "3": "Sucks or chews on finger foods.",
        "4": "Eats solid foods.",
        "5": "Cooperates in undressing and dressing.",
        "6": "Cooperates in washing of his/her hands and face.",
        "7": "Feeds himself/herself with a spoon; may spill.",
        "8": "Takes off his/her shoes and socks.",
        "9": "Drinks from a regular cup or glass; may spill.",
        "10": "Feeds himself/herself with a fork; may spill.",
        "11": "Takes off clothing that opens in the front.",
        "12": "Lets someone know when he/she needs changing.",
        "13": "Pulls up clothing with elastic waistbands.",
        "14": "Drinks from a regular cup or glass without spilling.",
        "15": "Urinates in a toilet or potty chair.",
        "16": "Washes and dries his/her hands.",
        "17": "Feeds himself/herself with a spoon without spilling.",
        "18": "Takes off pullover garments.",
        "19": "Puts on shoes; may be on the wrong feet and untied.",
        "20": "Puts on clothing that opens in the front.",
        "21": "Defecates in a toilet or potty chair.",
        "22": "Is toilet-trained during the day.",
        "23": "Puts on pullover garments.",
        "24": "Wipes/blows his/her nose using tissue, napkin, etc.",
        "25": "Washes and dries his/her face.",
        "26": "Wipes/cleans face and hands as needed when eating.",
        "27": "Puts clothing on right side forward/correct side out.",
        "28": "Is toilet-trained during the night.",
        "29": "Covers mouth and nose when coughing or sneezing.",
        "30": "Uses the toilet when needed without help.",
        "31": "Fastens snaps.",
        "32": "Brushes his/her teeth.",
        "33": "Buttons large buttons in the correct buttonholes.",
        "34": "Changes clothing that has become dirty/wet/smelly.",
        "35": "Connects and zips zippers.",
        "36": "Bathes or showers and dries himself/herself.",
        "37": "Puts shoes on the correct feet and ties or fastens.",
        "38": "Spreads food with a table knife.",
        "39": "Buttons small buttons in the correct buttonholes.",
        "40": "Shows awareness of healthy and unhealthy foods.",
        "41": "Finds and uses a restroom when away from home.",
        "42": "Turns faucets on and adjusts the water temperature.",
        "43": "Selects appropriate clothing for wet/cold weather.",
        "44": "Cuts easy-to-cut food with a table knife.",
        "45": "Shows awareness that exercise is good for people.",
        "46": "Washes and rinses his/her hair.",
        "47": "Chooses to exercise for health and/or enjoyment.",
        "48": "Uses the toilet before going out when needed.",
        "49": "Makes healthy eating choices.",
        "50": "Cuts harder-to-cut food with a sharp knife.",
        "51": "Plans for changes in weather before going out.",
    },
    "dom": {
        "1": "Is careful around hot objects.",
        "2": "Is careful when using sharp objects.",
        "3": "Wipes up his/her own spills.",
        "4": "Puts dirty clothes in the proper place to be washed.",
        "5": "Takes off or wipes dirty shoes before going inside.",
        "6": "Puts away his/her books, toys, etc. when done.",
        "7": "Washes his/her hands before preparing food.",
        "8": "Fully clears his/her dishes, etc. after eating.",
        "9": "Does at least two simple household chores.",
        "10": "Prepares a simple snack or meal.",
        "11": "Knows what to do in dangerous situations.",
        "12": "Puts his/her wet towel in the proper place after using.",
        "13": "Puts his/her clean clothes away where they belong.",
        "14": "Uses at least two simple kitchen appliances.",
        "15": "Cleans up after activities without being asked.",
        "16": "Straightens up a room without being asked.",
        "17": "Makes his/her bed and changes sheets on a routine basis.",
        "18": "Uses a stove or microwave for simple cooking.",
        "19": "Uses household cleaning products properly.",
        "20": "Prepares foods that need to be mixed before cooking.",
        "21": "Straightens up his/her room without being asked.",
        "22": "Does routine household repairs and maintenance without being asked.",
        "23": "Sews buttons and zippers onto clothing when asked.",
        "24": "Makes main meal without help.",
        "25": "Prepares his/her own budget for weekly expenses.",
        "26": "Can manage his/her finances without help.",
        "27": "Makes his/her own bed and changes sheets.",
        "28": "Reports to supervisor when late for work.",
        "29": "Reports to supervisor when absent from work due to illness.",
        "30": "Organizes monthly budget.",
    },
    "cmm": {
        "1": "Talks with a familiar person using a phone, etc.",
        "2": "Understands that money is used to buy things.",
        "3": "Counts at least 10 objects, one by one.",
        "4": "Stays near parent/caregiver when in public places.",
        "5": "Understands and follows car passenger safety rules.",
        "6": "Understands that a clock is used to tell time.",
        "7": "Operates at least two tech devices for entertainment.",
        "8": "Uses good manners when eating in public.",
        "9": "Says all seven days of the week in order.",
        "10": "Looks both ways when crossing streets/roads.",
        "11": "Respects the right to privacy for self and others.",
        "12": "Names a penny, nickel, dime, and quarter.",
        "13": "Says the current day of the week.",
        "14": "Understands that some items cost more than others.",
        "15": "Knows how to make an emergency call.",
        "16": "Obeys lights and signs when crossing streets/roads.",
        "17": "Tells time using a digital clock or watch.",
        "18": "Understands and follows community rules and laws.",
        "19": "Makes calls to others using a phone, computer, etc.",
        "20": "Knows the difference between different bills.",
        "21": "Understands signs/symbols used to indicate danger.",
        "22": "Identifies a specific date on a calendar.",
        "23": "Tells time to the nearest five minutes.",
        "24": "Knows the value of coins (riyal, piaster, halalas).",
        "25": "Accurately calculates change after buying something.",
        "26": "Uses the telephone to make calls without help.",
        "27": "Looks both ways before crossing a street or road on his/her own.",
        "28": "Answers the telephone in an appropriate manner.",
        "29": "Calls emergency services numbers when needed.",
        "30": "Obeys traffic lights and pedestrian crossing signs.",
        "31": "Calls the person requested or says he/she is not present.",
        "32": "Goes to the toilet when needed without anyone reminding him/her or helping.",
        "33": "Looks both ways before crossing street or road on his/her own.",
        "34": "Puts clean clothes in their proper place without being asked.",
        "35": "Cleans himself/herself without help.",
        "36": "Cleans household breakable items.",
        "37": "Dries himself/herself with a towel without help.",
        "38": "Fastens all buttons.",
        "39": "Helps in preparing food that needs to be mixed before cooking.",
        "40": "Knows the danger of accepting food or money from a stranger.",
        "41": "Ties his/her shoes without help.",
        "42": "Washes and bathes without help.",
        "43": "Looks both ways before crossing the street or road on his/her own.",
        "44": "Covers his/her mouth when coughing or sneezing.",
        "45": "Initiates contact with others by telephone.",
        "46": "Complies with traffic lights and pedestrian signals.",
        "47": "Dresses himself/herself completely including shoes and buttons.",
        "48": "Arranges his/her bed when asked.",
        "49": "Knows the current day of the week when asked.",
        "50": "Fastens the seatbelt in the car without relying on others.",
        "51": "Knows the value of coins.",
        "52": "Uses basic tools (hammer, comb, broom, etc.).",
        "53": "Knows left and right from another person.",
        "54": "Sets and clears the table when asked and without help.",
        "55": "Sweeps the floor and mops tiles when asked.",
        "56": "Uses emergency phone numbers when needed.",
        "57": "Orders a full meal for himself/herself at a restaurant.",
        "58": "Knows today's date when asked.",
        "59": "Wears appropriate clothing according to weather changes.",
        "60": "Avoids people with contagious diseases without needing to be reminded.",
        "61": "Tells the time to the nearest five minutes.",
        "62": "Grooms hair without anyone noticing or helping.",
        "63": "Uses the oven or microwave for simple things.",
        "64": "Uses cleaning products properly.",
        "65": "Accurately calculates what is left over after buying something.",
        "66": "Uses the telephone to make calls without help.",
        "67": "Trims fingernails without anyone noticing or helping.",
        "68": "Prepares food that needs to be mixed before cooking without help.",
        "69": "Can use a cell phone.",
        "70": "Arranges private room without being prompted.",
        "71": "Saves money to buy something and buys it on his/her own.",
        "72": "Cares about his/her general health.",
        "73": "Makes his/her own bed and changes sheets routinely.",
        "74": "Arranges other rooms without being asked.",
        "75": "Does routine household repairs and maintenance without being asked.",
        "76": "Sews buttons and zippers onto clothing when asked.",
        "77": "Prepares his/her own budget for weekly expenses.",
        "78": "Can manage his/her financial affairs without help.",
        "79": "Makes and prepares a main meal without help.",
        "80": "Arrives to his/her appointment on time.",
        "81": "Takes care of his/her appearance and clothing without anyone prompting.",
        "82": "Reports to supervisor if late for work.",
        "83": "Reports to supervisor when absent from work due to illness.",
        "84": "Organizes his/her monthly salary.",
        "85": "Sews simple things in clothing without help or prompting.",
        "86": "Takes full responsibility for doing a regular job.",
        "87": "Has a bank account and uses it responsibly.",
    },
    "ipr": {
        "1": "Looks at the face of parent/caregiver.",
        "2": "Smiles in response to a smile or friendly voice.",
        "3": "Recognizes family members or familiar others.",
        "4": "Smiles/vocalizes when someone familiar approaches.",
        "5": "Shows at least three different emotions.",
        "6": "Tries to interact with others.",
        "7": "Reaches back when a familiar person holds out arms.",
        "8": "Shows affection to familiar people.",
        "9": "Shows interest in children his/her age.",
        "10": "Checks to make sure parent/familiar other is nearby.",
        "11": "Recognizes himself/herself in a mirror or photo.",
        "12": "Smiles in response to praise or compliments.",
        "13": "Imitates parent/caregiver's facial expressions.",
        "14": "Recognizes emotions in others.",
        "15": "Imitates another's actions as they are being done.",
        "16": "Shows happiness, sympathy, or concern for others.",
        "17": "Tries to make friends with others his/her age.",
        "18": "Says how family members are related to him/her.",
        "19": "Uses words to express his/her emotions.",
        "20": "Maintains culturally appropriate eye contact.",
        "21": "When adults make small talk, answers politely.",
        "22": "Imitates another's actions several hours later.",
        "23": "Modulates his/her speech to fit the conversation.",
        "24": "Does things to try to please others.",
        "25": "Has a best friend or a few good friends.",
        "26": "Maintains an acceptable personal space.",
        "27": "Treats his/her friends well.",
        "28": "Talks with others about shared interests.",
        "29": "Maintains friendships over time.",
        "30": "Knows that others may have different likes/dislikes.",
        "31": "Starts small talk when meeting familiar people.",
        "32": "Chooses friends with good qualities.",
        "33": "Moves easily between topics in conversation.",
        "34": "Talks with others without interrupting or being rude.",
        "35": "Tells others what he/she is thinking and feeling.",
        "36": "Stays on topic in conversations when needed.",
        "37": "Congratulates others when good things happen.",
        "38": "Gives cards/gifts on family members' birthdays, etc.",
        "39": "Will do nonpreferred activities suggested by friends.",
        "40": "Starts conversations about things that interest others.",
        "41": "Participates in conversations on nonpreferred topics.",
        "42": "Responds to hints or indirect cues in conversation.",
        "43": "Provides additional explanation when others need it.",
    },
    "pla": {
        "1": "Responds when parent/caregiver is playful.",
        "2": "Shows interest in his/her surroundings.",
        "3": "Plays 'baby' games like peek-a-boo, patty-cake.",
        "4": "Plays near another child, each doing different things.",
        "5": "Copies the play of a child playing nearby.",
        "6": "Plays with peer(s) for 5 minutes under supervision.",
        "7": "Chooses to join other children who are playing.",
        "8": "Uses household objects for make-believe play.",
        "9": "Shares toys/possessions when told to do so.",
        "10": "Joins in with a group that is verbally welcoming.",
        "11": "Plays with peer(s) for 30 minutes under supervision.",
        "12": "Moves away from aggressive children nearby.",
        "13": "Plays simple make-believe with other children.",
        "14": "Plays with others at outdoor games with no score.",
        "15": "Asks others to play or spend time together.",
        "16": "Plays with other children with minimal supervision.",
        "17": "Takes turns in games or sports when asked.",
        "18": "Plays elaborate make-believe with other children.",
        "19": "Shares toys/possessions without having to be told.",
        "20": "Joins in with a group that is nonverbally welcoming.",
        "21": "Takes turns in games or sports without being asked.",
        "22": "Plays with others at simple games with scorekeeping.",
        "23": "Follows rules in games or sports without being told.",
        "24": "Plays simple card or board games based on chance.",
        "25": "Stays out of a group that is verbally nonwelcoming.",
        "26": "Asks permission before taking/using another's things.",
        "27": "Shows good sportsmanship in games or sports.",
        "28": "Gets together with peers at someone's home.",
        "29": "Stays out of a group that is nonverbally nonwelcoming.",
        "30": "Goes places with peers day or night with supervision.",
        "31": "Plays board/card/electronic games requiring skill.",
    },
    "cop": {
        "1": "Seeks comfort from a loved one when hurt or upset.",
        "2": "Seeks parent/caregiver when a stranger approaches.",
        "3": "Separates easily from parent/caregiver.",
        "4": "Transitions easily from one activity to another.",
        "5": "Responds politely when given something.",
        "6": "Is polite when asking for something.",
        "7": "Handles changes in routine without getting too upset.",
        "8": "Recovers quickly from a minor disappointment.",
        "9": "Uses words or gestures to express distress.",
        "10": "Apologizes for small, unintentional mistakes.",
        "11": "Acts appropriately when introduced to new people.",
        "12": "Asks for help when needed to do something.",
        "13": "Acts differently with people depending on familiarity.",
        "14": "Accepts helpful suggestions/solutions from others.",
        "15": "Apologizes with sincerity after hurting feelings.",
        "16": "Copies others' behavior when in a new situation.",
        "17": "Will compromise in order to get along with peers.",
        "18": "Controls anger when unexpected events disrupt plans.",
        "19": "Follows time limits imposed by parent/caregiver.",
        "20": "Realizes that people may hurt others unintentionally.",
        "21": "Adjusts behavior to avoid disrupting others nearby.",
        "22": "Controls anger when not getting his/her way.",
        "23": "Keeps his/her promises.",
        "24": "Controls anger when given constructive criticism.",
        "25": "Realizes that friendly acting people may intend harm.",
        "26": "Respects others' time.",
        "27": "Uses appropriate etiquette without needing to be told.",
        "28": "Watches TV or listens to radio for information.",
        "29": "Goes to some after-school activities when accompanied by an adult.",
        "30": "Is able to evaluate the consequences of actions before making decisions.",
        "31": "Apologizes for wrong behavior or mistakes.",
        "32": "Remembers special occasions of family members and close friends.",
        "33": "Initiates conversations on topics that are important to others.",
        "34": "Has a hobby.",
        "35": "Returns money from someone who cares for him/her and asks for it back.",
        "36": "Responds to hints or indirect cues in conversation.",
    },
    "gmo": {
        "1": "Sits for at least 1 minute with his/her back supported.",
        "2": "Rolls over from his/her back onto his/her stomach.",
        "3": "Sits unsupported for at least 1 minute.",
        "4": "Moves, scoots, or crawls across the floor.",
        "5": "Sits unsupported for at least 10 minutes.",
        "6": "Stands supported for at least 5 seconds.",
        "7": "Pulls himself/herself up to standing position.",
        "8": "Stands supported and reaches without falling.",
        "9": "Takes steps while holding on to furniture, etc.",
        "10": "Crawls up stairs.",
        "11": "Stands unsupported for at least 1 minute.",
        "12": "Takes at least two steps without support.",
        "13": "Stands unsupported and reaches without falling.",
        "14": "Walks to get around; does not need support.",
        "15": "Safely climbs on and off low objects.",
        "16": "Crawls backwards down stairs or scoots on bottom.",
        "17": "Squats or bends to pick up objects without falling.",
        "18": "Throws a ball with one hand.",
        "19": "Safely gets on and off an adult-sized chair.",
        "20": "Runs without falling, though may be uncoordinated.",
        "21": "Walks up stairs, putting both feet on each step.",
        "22": "Kicks a ball while standing.",
        "23": "Walks two or more blocks without rest or support.",
        "24": "Walks down stairs, putting both feet on each step.",
        "25": "Jumps off the ground with both feet without falling.",
        "26": "Runs smoothly without falling.",
        "27": "Safely climbs up and down high objects.",
        "28": "Walks carefully on a slippery or uneven walkway.",
        "29": "Jumps forward at least three times with both feet.",
        "30": "Runs smoothly, changing speed and direction.",
        "31": "Catches a beach ball-sized ball from 2 or 3 feet away.",
        "32": "Walks up stairs, alternating feet.",
        "33": "Walks down stairs, alternating feet.",
        "34": "Climbs a flight of stairs at a normal pace.",
        "35": "Pedals a tricycle or similar vehicle for at least 6 feet.",
        "36": "Hops on one foot without falling; may need support.",
        "37": "Pedals a tricycle or similar vehicle around corners.",
        "38": "Catches a beach ball-sized ball from 6 feet or more.",
        "39": "Hops forward on one foot with ease without support.",
        "40": "Catches a baseball-sized ball from 2 or 3 feet away.",
        "41": "Rides a balance bike or bicycle with training wheels.",
        "42": "Catches a baseball-sized ball from 10 feet or more.",
        "43": "Rides a regular bicycle without falling.",
    },
    "fmo": {
        "1": "Reaches for a toy or object.",
        "2": "Picks up objects using one or both hands.",
        "3": "Moves an object from one hand to the other.",
        "4": "Removes an object from a box or other container.",
        "5": "Picks up small objects with his/her thumb and fingers.",
        "6": "Picks up and hands a small toy or object to someone.",
        "7": "Puts an object into a box or other container.",
        "8": "Marks on paper with a crayon, pen, or pencil.",
        "9": "Opens doors that require only pushing or pulling.",
        "10": "Stacks at least four blocks or other small objects.",
        "11": "Turns book or magazine pages one by one.",
        "12": "Unwraps small objects.",
        "13": "Opens doors by turning a doorknob or handle.",
        "14": "Uses a twisting hand-wrist motion.",
        "15": "Holds a crayon/pen/pencil properly for drawing, etc.",
        "16": "Presses buttons accurately on a keyboard or screen.",
        "17": "Opens and closes scissors with one hand.",
        "18": "Draws a circle freehand from an example.",
        "19": "Colors simple shapes or animals.",
        "20": "Draws more than one recognizable form.",
        "21": "Pours liquid from one container to another.",
        "22": "Draws a square freehand from an example.",
        "23": "Uses scissors to cut paper along a straight line.",
        "24": "Draws a triangle freehand from an example.",
        "25": "Uses an eraser without tearing the paper.",
        "26": "Cuts out simple shapes.",
        "27": "Colors simple pictures completely inside the lines.",
        "28": "Colors a complex scene using two or more colors.",
        "29": "Draws a straight line using a ruler or straightedge.",
        "30": "Ties a knot.",
        "31": "Cuts out complex shapes.",
        "32": "Ties a secure bow.",
        "33": "Manipulates very small objects.",
        "34": "Assembles/creates complex toy structures, crafts, etc.",
    },
}

# ═══════════════════════════════════════════════════════════
# ARABIC ITEMS (Vineland-3 EN translated in Vineland-II Arafa style/tone)
# ═══════════════════════════════════════════════════════════
ITEMS_AR = {
    "rec": {
        "1": "يحرك عينيه ورأسه نحو صوت القائم على رعايته.",
        "2": "ينظر عندما يشير القائم على رعايته لاستقطاب انتباهه.",
        "3": "يستجيب عند سماعه اسمه يُنادى.",
        "4": "يتابع نظرة القائم على رعايته أو معلمه أو إشارته بالإصبع.",
        "5": "يظهر فهمه بوضوح لعشر كلمات على الأقل.",
        "6": "يفهم ثلاث إيماءات أساسية على الأقل.",
        "7": "يفهم كلمة 'لا'.",
        "8": "يفهم ثلاثة تعبيرات وجهية على الأقل.",
        "9": "يفهم كلمة 'نعم'.",
        "10": "يُصغي بانتباه للتعليمات.",
        "11": "يُحدد ثلاثة أشياء حقيقية على الأقل.",
        "12": "يفهم خمسين كلمة على الأقل.",
        "13": "يستجيب لنبرة الكلمات المنطوقة.",
        "14": "يُحدد ثلاثة أجزاء من جسمه على الأقل عند الطلب.",
        "15": "يُنفذ تعليمات تشتمل على فعل واحد وشيء واحد.",
        "16": "يفهم ثلاث إيماءات أكثر تقدماً على الأقل.",
        "17": "يُحدد ثلاثة أشياء مصورة على الأقل.",
        "18": "يُحدد ثلاثة أجزاء من الجسم في صورة على الأقل.",
        "19": "يستجيب لأسئلة تبدأ بـ'ماذا'.",
        "20": "يستجيب لأسئلة تبدأ بـ'من'.",
        "21": "يُحدد ثلاثة أفعال مصورة على الأقل.",
        "22": "يستجيب لأسئلة تبدأ بـ'أين'.",
        "23": "يُنفذ تعليمات تشتمل على فعلين مترابطين.",
        "24": "يُنفذ تعليمات تشتمل على فعل واحد وشيئين.",
        "25": "يُنفذ التعليمات التي تستخدم صيغة 'إذا' الشرطية.",
        "26": "يستمع إلى قصة لمدة خمس عشرة دقيقة على الأقل.",
        "27": "يستجيب لأسئلة تبدأ بـ'لماذا'.",
        "28": "يُنفذ تعليمات تشتمل على فعلين غير مترابطين.",
        "29": "يستجيب لأسئلة تبدأ بـ'متى'.",
        "30": "يُشاهد برنامجاً تلفزيونياً لمدة ثلاثين دقيقة على الأقل.",
        "31": "يُحدد اليمين والشمال على جسمه.",
        "32": "يُنفذ تعليمات تشتمل على ثلاثة أفعال.",
        "33": "يُشاهد برنامجاً تلفزيونياً لمدة ستين دقيقة على الأقل.",
        "34": "يفهم السخرية والتهكم.",
        "35": "يُصغي بانتباه لحديث عام مدته خمس عشرة دقيقة.",
        "36": "يُنفذ تعليمات تتضمن اليمين والشمال.",
        "37": "يتذكر أن يقوم بشيء ما بعد ساعة.",
        "38": "يتذكر أن يقوم بشيء ما بعد عدة ساعات.",
        "39": "يُصغي بانتباه لحديث عام مدته ثلاثون دقيقة.",
    },
    "exp": {
        "1": "يُصدر أصواتاً تعبر عن السعادة.",
        "2": "يبكي أو يُعبر عن الانزعاج.",
        "3": "يُصوّت أو يُشير للفت الانتباه.",
        "4": "يُصدر ثلاثة أصوات كلامية أحادية المقطع على الأقل.",
        "5": "يُثرثر في سلاسل من الأصوات.",
        "6": "يُصوّت أو يُشير لإيقاف نشاط أو الاستمرار فيه.",
        "7": "يقول: أبو، أمو، أو اسم القائم على رعايته.",
        "8": "يستخدم ثلاث إيماءات أساسية على الأقل.",
        "9": "يُكرر أو يحاول تكرار الكلمات الشائعة.",
        "10": "يقول 'لا'.",
        "11": "يُسمي ثلاثة أشياء على الأقل.",
        "12": "يطلب بكلمة واحدة.",
        "13": "يُسمي عشرة أشياء على الأقل.",
        "14": "يقول 'نعم'.",
        "15": "يُسمي ثلاثة أفعال على الأقل.",
        "16": "يُنادي الإخوة والأقران والزملاء بأسمائهم أو ألقابهم.",
        "17": "يتكلم بخمسين كلمة مألوفة على الأقل.",
        "18": "يستخدم عبارات تتضمن اسماً وفعلاً.",
        "19": "يقول اسمه الأول أو لقبه.",
        "20": "يستخدم الضمائر للإشارة إلى نفسه.",
        "21": "يستخدم الصفات البسيطة لوصف الأشياء.",
        "22": "يقول ما يفعله بجمل بسيطة.",
        "23": "يستخدم ثلاث إيماءات أكثر تقدماً على الأقل.",
        "24": "يستخدم النفي في الجمل.",
        "25": "يذكر سنه عندما يُسأل.",
        "26": "يستخدم صيغ الملكية في عباراته أو جمله.",
        "27": "يستخدم كلمة 'و' في عباراته أو جمله.",
        "28": "يسأل أسئلة تبدأ بـ'من'.",
        "29": "يستخدم صيغة الجمع.",
        "30": "يستخدم الضمائر للإشارة إلى الآخرين.",
        "31": "يستخدم كلمات 'في' و'على' و'تحت'.",
        "32": "يسأل أسئلة تبدأ بـ'لماذا'.",
        "33": "يقول اسمه الأول والأخير عند الطلب.",
        "34": "يستخدم الضمائر بشكل صحيح.",
        "35": "يسأل أسئلة تبدأ بـ'متى'.",
        "36": "يستخدم كلمة 'لأن' في عباراته أو جمله.",
        "37": "يقول سنه في عيد ميلاده القادم عند الطلب.",
        "38": "يستخدم أفعال الماضي.",
        "39": "يروي الأجزاء الأساسية من قصة مألوفة.",
        "40": "يستخدم كلمات 'خلف' و'أمام' و'بين'.",
        "41": "يُعطي تعليمات بسيطة من خطوة أو خطوتين.",
        "42": "يستخدم جملاً مركبة تُربط بـ'و' أو 'لكن'.",
        "43": "يستخدم معلوماته أو آراءه الخاصة في التعليق.",
        "44": "يروي تفاصيل تجارب يومية.",
        "45": "يروي تفاصيل تجارب مررت به مرة واحدة.",
        "46": "يقول الشهر واليوم من عيد ميلاده.",
        "47": "يوضح المعنى بإعادة الصياغة عند الحاجة.",
        "48": "يقول عنوان منزله الكامل بشكل صحيح.",
        "49": "يُعطي تعليمات معقدة من ثلاث خطوات أو أكثر.",
    },
    "wrn": {
        "1": "يمسك الكتاب ويقلّب صفحاته بالطريقة الصحيحة.",
        "2": "يتعرف على إشارة أو رمز أو علامة بسيطة على الأقل.",
        "3": "يتعرف على حرف أو أكثر من حروف الهجاء.",
        "4": "يتعرف على اسمه مكتوباً.",
        "5": "يتعرف على عشرة حروف هجائية على الأقل.",
        "6": "يفهم كيفية كتابة لغته.",
        "7": "يكتب في الاتجاه الصحيح للغته.",
        "8": "ينسخ اسمه الأول بشكل صحيح.",
        "9": "ينسخ كلمات بسيطة من نموذج بشكل صحيح.",
        "10": "يتعرف على جميع الحروف الهجائية بصيغتيها.",
        "11": "يكتب حروف الهجاء باتجاهها الصحيح.",
        "12": "يقرأ عشر كلمات على الأقل.",
        "13": "يكتب اسمه الأول والأخير من الذاكرة.",
        "14": "يقرأ جملاً من ثلاث كلمات أو أكثر بصوت عالٍ.",
        "15": "ينسخ عبارات من أربع كلمات أو أكثر بشكل صحيح.",
        "16": "يكتب عشر كلمات بسيطة من الذاكرة على الأقل.",
        "17": "يقرأ قصصاً بسيطة بصوت عالٍ.",
        "18": "يكتب جملاً بسيطة من ثلاث كلمات أو أكثر.",
        "19": "يكتب عشرين كلمة من الذاكرة على الأقل.",
        "20": "يقرأ بمستوى الصف الثاني الابتدائي أو أعلى.",
        "21": "يكتب رسالة مراسلة بسيطة من ثلاث جمل.",
        "22": "يتابع القراءة في قصة.",
        "23": "يقرأ ويفهم فقرات بسيطة.",
        "24": "يكتب فقرة من خمس جمل أو أكثر.",
        "25": "يقرأ من كتب بمستوى الصف الرابع أو أعلى.",
        "26": "يكتب الكلمات بشكل مترابط ومتسق في معظم الأحيان.",
        "27": "يقرأ الكتب بمفرده للمتعة.",
        "28": "يكتب موضوعات بسيطة في مستوى الصف الأول.",
        "29": "يقرأ الصحف بمستوى الكبار.",
        "30": "يكتب خطابات تتعلق بالعمل.",
        "31": "يستخدم القاموس.",
        "32": "يستخدم الفهارس في الكتب.",
        "33": "يكتب موضوعات إنشائية.",
        "34": "يكتب العنوان على ظرف الخطابات.",
        "35": "يستخدم قوائم المفردات من الكتب.",
        "36": "يقرأ قصص الكبار في الجرائد.",
        "37": "يكتب كل حروف الهجاء من الذاكرة.",
        "38": "يقرأ على الأقل ثلاث كلمات شفهة.",
        "39": "يذكر تاريخ ميلاده باليوم والشهر عندما يُسأل.",
        "40": "يستخدم صيغة الجمع والتكسير.",
        "41": "يكتب اسمه الأول والأخير.",
        "42": "يذكر هاتف المنزل عندما يُسأل.",
        "43": "يستطيع إعطاء عنوانه كاملاً بما فيه اسم المدينة والمنطقة عندما يُسأل.",
        "44": "يقرأ على الأقل عشر كلمات بصوت عادٍ.",
        "45": "يكتب على الأقل عشر كلمات من الذاكرة.",
        "46": "يُعبر عن أفكاره بأكثر من طريقة وبدون مساعدة.",
        "47": "يقرأ قصة بسيطة بصوت مرتفع.",
        "48": "يكتب جملة بسيطة تتكون من ثلاث أو أربع كلمات.",
        "49": "يتابع حديثاً عاماً في المدرسة أو خارجها لمدة تزيد عن 15 دقيقة.",
        "50": "يبادر بالقراءة بمفرده.",
        "51": "يقرأ من الكتاب إلى مستوى الصف الثاني الابتدائي على الأقل.",
        "52": "يرتب الكلمات ترتيباً أبجدياً حسب الحرف الأول.",
        "53": "يكتب خطابات قصيرة أو رسائل.",
        "54": "يصف للآخرين الأماكن التي يحتاج الوصول إليها السير في اتجاهات متعددة.",
        "55": "يكتب موضوعات ذات مستوى أولى بسيط.",
        "56": "يقرأ من الكتاب إلى مستوى الصف الرابع الابتدائي على الأقل.",
        "57": "يكتب الكلمات بشكل مترابط ومتصل في معظم الأحيان.",
        "58": "يستخدم القاموس.",
        "59": "يستخدم الفهارس في الكتب التي يقرؤها.",
        "60": "يكتب موضوعات الإنشاء.",
        "61": "يكتب العنوان على مظاريف الخطابات بدقة.",
        "62": "يستخدم قوائم المفردات من الكتب.",
        "63": "يقرأ قصص الكبار في الجرائد.",
        "64": "لديه أهداف بعيدة المدى ويصف خططاً بالتفصيل للوصول إلى هذه الأهداف.",
        "65": "يقرأ مجلات الكبار أو قصص المجلات الأسبوعية.",
        "66": "يكتب خطابات تتعلق بالعمل.",
    },
    "per": {
        "1": "يفتح فمه عند رؤية الغذاء أو الرضاعة أو الأكل.",
        "2": "يلتع فمه عندما تقدم له ملعقة.",
        "3": "يأخذ الأكل من الملعقة بفمه.",
        "4": "يمص أو يمضغ رقائق القمح (كورن فليكس).",
        "5": "يأكل الطعام الجامد (الشيكولاته والموز وغيرهما).",
        "6": "يشرب من الكوب بدون مساعدة.",
        "7": "يتناول طعامه بنفسه بدون مساعدة.",
        "8": "يفهم أن الأشياء الساخنة خطرة.",
        "9": "يعبر عن بلل أو اتساع في ملابسه بالإشارات أو الصوت.",
        "10": "يمص بالمزاز.",
        "11": "يسمح لمن يقوم برعايته بتنظيف أنفه.",
        "12": "يخلع الجاكيت أو القميص بدون مساعدة.",
        "13": "يأكل بالملعقة دون أن يتبعثر.",
        "14": "يُبدي رغبة في تغيير الملابس عندما تكون مبللة أو قذرة.",
        "15": "يتبول في الحمام باستخدام كرسي الحمام.",
        "16": "يستحم بمساعدة شخص آخر.",
        "17": "يتبرز في الحمام باستخدام كرسي الحمام.",
        "18": "يطلب استخدام الحمام.",
        "19": "يرتدي بنطلون له حزام مطاطي.",
        "20": "يُدرك معنى قيمة النقود.",
        "21": "يضع حاجياته في الأماكن المخصصة عندما يُطلب منه ذلك.",
        "22": "يتحكم في عملية التبول ليلاً.",
        "23": "يشرب الماء من الحنفية (الصنبور) دون مساعدة.",
        "24": "ينظف أسنانه دون مساعدة.",
        "25": "يُدرك وظيفة الساعة سواء العادية أو الرقمية.",
        "26": "يساعد بالأعمال المنزلية الخفيفة عندما يُطلب منه ذلك.",
        "27": "يغسل ويجفف وجهه دون مساعدة.",
        "28": "يلبس الحذاء في القدم الصحيح دون مساعدة.",
        "29": "يُجيب على الهاتف بطريقة مناسبة.",
        "30": "يقوم بارتداء ملابسه بمفرده ماعدا ربط الحذاء.",
        "31": "يستدعي للهاتف الشخص المطلوب أو يُجيب بأنه غير موجود.",
        "32": "يذهب إلى الحمام عند الحاجة دون أن يذكره أحد أو يساعده.",
        "33": "ينظر إلى جانبي الطريق قبل عبوره الشارع أو الطريق بمفرده.",
        "34": "يضع الملابس النظيفة جانباً عندما يُطلب منه ذلك دون مساعدة.",
        "35": "ينظف نفسه دون مساعدة.",
        "36": "ينظف الأدوات المنزلية القابلة للكسر.",
        "37": "يجفف نفسه بالمنشفة دون مساعدة.",
        "38": "يقفل جميع أزرار ملابسه.",
        "39": "يساعد في تحضير الطعام الذي يحتاج إلى خلط عند الإعداد.",
        "40": "يعي خطورة قبوله للتوصيل أو الطعام أو النقود من شخص غريب.",
        "41": "يربط حذاءه دون مساعدة.",
        "42": "يغتسل ويستحم دون مساعدة.",
        "43": "ينظر إلى جانبي الطريق قبل عبوره الشارع أو الطريق بمفرده.",
        "44": "يغطي فمه عند الكحة أو العطس.",
        "45": "يبادر بالاتصال بالآخرين بواسطة الهاتف.",
        "46": "يلتزم بإشارات المرور وبإشارات المشاة.",
        "47": "يرتدي ملابسه بالكامل بما في ذلك لبس الحذاء وربط الأزرار.",
        "48": "يرتب سريره عندما يُطلب منه ذلك.",
        "49": "يعرف ما هو اليوم الحالي من الأسبوع عندما يُطلب منه ذلك.",
        "50": "يربط حزام السلامة في السيارة دون الاعتماد على الآخرين.",
        "51": "يعرف قيمة العملات المعدنية.",
    },
    "dom": {
        "1": "يحذر من الأشياء الساخنة.",
        "2": "يكون حذراً عند استخدام الأشياء الحادة.",
        "3": "يمسح ما سكبه من سوائل.",
        "4": "يضع ملابسه الوسخة في المكان المخصص للغسيل.",
        "5": "يخلع أو يمسح حذاءه المتسخ قبل الدخول للمنزل.",
        "6": "يضع كتبه وألعابه في مكانها عند الانتهاء.",
        "7": "يغسل يديه قبل تحضير الطعام.",
        "8": "يُزيل صحونه بعد الأكل بشكل كامل.",
        "9": "يقوم بعملين من الأعمال المنزلية البسيطة على الأقل.",
        "10": "يُعد وجبة خفيفة أو وجبة بسيطة.",
        "11": "يعرف ما يفعله في المواقف الخطرة.",
        "12": "يضع منشفته المبللة في مكانها المناسب بعد استخدامها.",
        "13": "يضع ملابسه النظيفة في مكانها الصحيح.",
        "14": "يستخدم جهازين من الأجهزة المنزلية البسيطة على الأقل.",
        "15": "يُرتب بعد الأنشطة دون أن يُطلب منه ذلك.",
        "16": "يُرتب غرفةً دون أن يُطلب منه ذلك.",
        "17": "يرتب سريره الخاص ويغير الملاءة بشكل روتيني.",
        "18": "يستخدم الفرن أو الميكروويف في الطهي البسيط.",
        "19": "يستخدم أدوات التنظيف المنزلية بطريقة صحيحة.",
        "20": "يُعد الأطعمة التي تحتاج إلى خلط قبل الطهي.",
        "21": "يرتب غرفته الخاصة دون أن ينبه إلى ذلك.",
        "22": "يقوم بالإصلاحات المنزلية المعتادة وأعمال الصيانة دون أن يُطلب منه ذلك.",
        "23": "يخيط الأزرار والمشابك في ملابسه عندما يُطلب منه ذلك.",
        "24": "يعد ويُحضّر الوجبة الرئيسية دون مساعدة.",
        "25": "يُعد ميزانية لمصروفاته الأسبوعية.",
        "26": "يستطيع أن يُنظم شؤونه المالية بدون مساعدة.",
        "27": "يرتب سريره الخاص ويغير الملاءة.",
        "28": "يُبلغ رئيسه في العمل إذا كان سيتأخر في الوصول إلى العمل.",
        "29": "يُبلغ رئيسه في العمل عندما يتغيب عن العمل بسبب المرض.",
        "30": "يُعد ميزانية لمصروفاته الشهرية.",
    },
    "cmm": {
        "1": "يتحدث مع شخص مألوف باستخدام الهاتف وما شابهه.",
        "2": "يفهم أن النقود تُستخدم لشراء الأشياء.",
        "3": "يعد عشرة أشياء على الأقل، شيئاً شيئاً.",
        "4": "يبقى قريباً من والديه أو مَن يرعاه عند التواجد في الأماكن العامة.",
        "5": "يفهم ويتبع قواعد السلامة داخل السيارة.",
        "6": "يفهم أن الساعة تُستخدم لمعرفة الوقت.",
        "7": "يُشغّل جهازين تقنيين للترفيه على الأقل.",
        "8": "يستخدم آداب السلوك الحسنة عند تناول الطعام في الأماكن العامة.",
        "9": "يذكر أيام الأسبوع السبعة بالترتيب.",
        "10": "ينظر كلا الجانبين عند عبور الشوارع أو الطرق.",
        "11": "يحترم حق الخصوصية لنفسه وللآخرين.",
        "12": "يُسمي قطع النقود المعدنية المختلفة.",
        "13": "يذكر اليوم الحالي من الأسبوع.",
        "14": "يفهم أن بعض الأشياء تكلف أكثر من غيرها.",
        "15": "يعرف كيف يُجري مكالمة طوارئ.",
        "16": "يُطيع إشارات المرور وعلامات العبور عند اجتياز الشوارع.",
        "17": "يُحدد الوقت باستخدام ساعة رقمية.",
        "18": "يفهم ويتبع قواعد وقوانين المجتمع.",
        "19": "يُجري مكالمات للآخرين عبر الهاتف أو الكمبيوتر.",
        "20": "يعرف الفرق بين الأوراق النقدية المختلفة.",
        "21": "يفهم العلامات والرموز المستخدمة للتنبيه على الخطر.",
        "22": "يُحدد تاريخاً بعينه في التقويم.",
        "23": "يُحدد الوقت بزيادة خمس دقائق.",
        "24": "يعرف قيمة العملات المعدنية (الريال، القرش، الهللة).",
        "25": "يحسب بدقة ما تبقى من نقود بعد الشراء.",
        "26": "يستخدم التليفون لإجراء المكالمات وبدون مساعدة.",
        "27": "ينظر إلى جانبي الطريق قبل عبوره الشارع أو الطريق بمفرده.",
        "28": "يُجيب على الهاتف بطريقة مناسبة.",
        "29": "يستخدم أرقام هواتف الطوارئ عند الحاجة.",
        "30": "يلتزم بإشارات المرور وبإشارات المشاة.",
        "31": "يستدعي للهاتف الشخص المطلوب أو يُجيب بأنه غير موجود.",
        "32": "يذهب إلى الحمام عند الحاجة دون أن يذكره أحد أو يساعده.",
        "33": "ينظر إلى جانبي الطريق قبل عبوره الشارع أو الطريق بمفرده.",
        "34": "يضع الملابس النظيفة جانباً عندما يُطلب منه ذلك دون مساعدة.",
        "35": "ينظف نفسه دون مساعدة.",
        "36": "ينظف الأدوات المنزلية القابلة للكسر.",
        "37": "يجفف نفسه بالمنشفة دون مساعدة.",
        "38": "يقفل جميع أزرار ملابسه.",
        "39": "يساعد في تحضير الطعام الذي يحتاج إلى خلط عند الإعداد.",
        "40": "يعي خطورة قبوله للتوصيل أو الطعام أو النقود من شخص غريب.",
        "41": "يربط حذاءه دون مساعدة.",
        "42": "يغتسل ويستحم دون مساعدة.",
        "43": "ينظر إلى جانبي الطريق قبل عبوره الشارع أو الطريق بمفرده.",
        "44": "يغطي فمه عند الكحة أو العطس.",
        "45": "يبادر بالاتصال بالآخرين بواسطة الهاتف.",
        "46": "يلتزم بإشارات المرور وبإشارات المشاة.",
        "47": "يرتدي ملابسه بالكامل بما في ذلك لبس الحذاء وربط الأزرار.",
        "48": "يرتب سريره عندما يُطلب منه ذلك.",
        "49": "يعرف ما هو اليوم الحالي من الأسبوع عندما يُطلب منه ذلك.",
        "50": "يربط حزام السلامة في السيارة دون الاعتماد على الآخرين.",
        "51": "يعرف قيمة العملات المعدنية.",
        "52": "يستخدم الأدوات الأساسية (المطرقة، الكمشة، المكنسة... إلخ).",
        "53": "يعرف شمال ويمين شخص آخر.",
        "54": "يُعد ويُرتب طاولة الطعام عندما يُطلب منه ذلك وبدون مساعدة.",
        "55": "يكنس الأرض ويمسح البلاط عندما يُطلب منه ذلك.",
        "56": "يستخدم أرقام هواتف الطوارئ عند الحاجة.",
        "57": "يطلب لنفسه وجبة كاملة في المطعم.",
        "58": "يعرف تاريخ اليوم عندما يُسأل عنه.",
        "59": "يلبس الملابس الملائمة حسب توقعاته لتغيرات الطقس.",
        "60": "يتجنب الأشخاص المصابين بالأمراض المعدية دون الحاجة لتذكيره.",
        "61": "يُحدد الوقت بزيادة خمس دقائق.",
        "62": "يهتم بتصفيف شعره دون أن ينبه أحد ودون مساعدة.",
        "63": "يستخدم الفرن أو الميكروويف عند عمل الأشياء البسيطة.",
        "64": "يستخدم أدوات التنظفة (منظفات المنزل) بدقة وبطريقة صحيحة.",
        "65": "يحسب بدقة ما تبقى من نقود بعد الشراء بالريال.",
        "66": "يستخدم التليفون لإجراء المكالمات وبدون مساعدة.",
        "67": "يقلم أظافره دون أن ينبه أحد ودون مساعدة.",
        "68": "يُعد الأطعمة التي تحتاج إلى خلط قبل الطهي بدون مساعدة.",
        "69": "يستطيع استخدام هاتف الصلة.",
        "70": "يرتب غرفته الخاصة دون أن ينبه إلى ذلك.",
        "71": "يدخر نقوداً لشراء شيء ما ويقوم بشراء شيئاً محبباً إلى نفسه.",
        "72": "يهتم بصحته العامة.",
        "73": "يرتب سريره الخاص ويغير الملاءة بشكل روتيني.",
        "74": "يرتب غرف الغير بانتظام دون أن يُطلب منه ذلك.",
        "75": "يقوم بالإصلاحات المنزلية المعتادة وأعمال الصيانة دون أن يُطلب منه ذلك.",
        "76": "يخيط الأزرار والمشابك في ملابسه عندما يُطلب منه ذلك.",
        "77": "يُعد ميزانية لمصروفاته الأسبوعية.",
        "78": "يستطيع أن يُنظم شؤونه المالية بدون مساعدة.",
        "79": "يعد ويُحضّر الوجبة الرئيسية دون مساعدة.",
        "80": "يصل إلى عمله في الموعد المحدد.",
        "81": "يهتم بشكله وملابسه الخاصة دون أن ينبه أحد إلى ذلك.",
        "82": "يُبلغ رئيسه في العمل إذا كان سيتأخر في الوصول إلى العمل.",
        "83": "يُبلغ رئيسه في العمل عندما يتغيب عن العمل بسبب المرض.",
        "84": "يُنظم راتبه طبقاً لمصروفاته الشهرية.",
        "85": "يخيط بعض الأشياء البسيطة في ملابسه دون مساعدة أو تنبيه.",
        "86": "يتحمل بمسؤولية كاملة واجبات القيام بعمل منتظم.",
        "87": "له حساب جارٍ في البنك ويستخدمه استخداماً مسئولاً.",
    },
    "ipr": {
        "1": "ينظر إلى وجه الشخص الذي يقوم برعايته.",
        "2": "يستجيب لصوت الشخص الذي يقوم برعايته والأشخاص الآخرين.",
        "3": "يُفرق بين الشخص الذي يقوم برعايته والأشخاص الآخرين.",
        "4": "يُظهر اهتماماً بالأشياء الجديدة أو الأشخاص الجدد.",
        "5": "يُعبر عن عاطفتين أو أكثر مثل الرضا والحزن أو الخوف.",
        "6": "يتوقع عندما يرى من يقوم برعايته أن يرفعه إلى أعلى.",
        "7": "يُظهر عاطفة للناس المألوفين.",
        "8": "يُظهر اهتماماً تجاه الأشخاص والأطفال غير الإخوان.",
        "9": "يصل إلى الأشخاص المألوفين.",
        "10": "يلعب بالدمى أو الأشياء الأخرى بمفرده أو مع الآخرين.",
        "11": "يمارس الألعاب التي بها تفاعل بسيط مع الأطفال الآخرين.",
        "12": "يستخدم بعض أدوات المنزل ليلعب بها.",
        "13": "يُبدي اهتماماً بأنشطة الآخرين.",
        "14": "يُقلد بعض حركات الكبار (إشارة السلام، التصفيق).",
        "15": "يضحك أو يبتسم بشكل مناسب كاستجابة لعبارات مشجعة.",
        "16": "يُنادي اثنين من المعروفين على الأقل بأسمائهم.",
        "17": "يُبدي رغبة في إرضاء من يقوم برعايته.",
        "18": "يُشارك على الأقل في لعبة أو نشاط واحد مع الآخرين.",
        "19": "يُقلد الأعمال المعقدة بعد ساعات من مشاهدته لشخص يؤديها أمامه.",
        "20": "يُقلد عبارات الكبار التي سمعها في مناسبات سابقة.",
        "21": "يُشارك في الألعاب الإيهامية (استخدام العصي كيف) بمفرده أو مع الآخرين.",
        "22": "يُبدي تفضيلاً لبعض الأصدقاء دون الآخرين.",
        "23": "يقول لو سمحت عندما يُطلب شيئاً.",
        "24": "تظهر عليه مشاعر السعادة والخوف، الحزن، أو الغضب.",
        "25": "يُعرّف الأشخاص الآخرين بخصائص أخرى غير الاسم عندما يُطلب منه ذلك.",
        "26": "يُشرك الآخرين في اللعب بألعابه الخاصة دون أن يُطلب منه ذلك.",
        "27": "يذكر برنامجاً تلفزيونياً أو أكثر عندما يُطلب منه ذلك ويُحدد اليوم والقناة.",
        "28": "يتبع قوانين الألعاب البسيطة دون أن يُطلب منه ذلك.",
        "29": "لديه صديق مفضل.",
        "30": "يلتزم بأنظمة المدرسة أو المؤسسة.",
        "31": "يستجيب لفظياً وإيجابياً لتشجيع الآخرين.",
        "32": "يعتذر عن أخطائه غير المقصودة.",
        "33": "لديه مجموعة من الأصدقاء.",
        "34": "يتبع قواعد وقوانين المجتمع.",
        "35": "يمارس ألعاب الورق أو الألعاب التي تحتاج إلى مهارة واتخاذ قرار.",
        "36": "لا يتحدث والطعام في فمه.",
        "37": "لديه صديق من نفس الجنس (ذكر – أنثى) مفضل على غيره.",
        "38": "يستجيب بطريقة مناسبة عندما يُقدم له أشخاص غرباء.",
        "39": "يبادر بشراء ألعاب أو هدايا لمن يقوم برعايته أو أحد أفراد الأسرة.",
        "40": "يحلظ الأسرار ويكتمها لأكثر من يوم.",
        "41": "يُعيد ألعابه المستعارة وكذلك النقود أو الكتب لزملائه.",
        "42": "يُنهي المحادثة مع الآخرين بطريقة مناسبة.",
        "43": "يلتزم بتنظيم الوقت الذي يضمه لمن لم يقم برعايته.",
    },
    "pla": {
        "1": "يستجيب عندما يقوم القائم على رعايته بمداعبته.",
        "2": "يُظهر اهتماماً بمحيطه.",
        "3": "يلعب ألعاب الأطفال مثل لعبة الاستخباء وتصفيق الأكف.",
        "4": "يلعب بجانب طفل آخر وكلاهما يفعل أشياء مختلفة.",
        "5": "يُقلد لعب طفل يلعب بالقرب منه.",
        "6": "يلعب مع أقرانه من 5 دقائق تحت الإشراف.",
        "7": "يختار الانضمام إلى أطفال آخرين يلعبون.",
        "8": "يستخدم أدوات المنزل في اللعب الإيهامي.",
        "9": "يتشارك في الألعاب والممتلكات عندما يُطلب منه ذلك.",
        "10": "ينضم إلى مجموعة تُرحب به لفظياً.",
        "11": "يلعب مع أقرانه لمدة 30 دقيقة تحت الإشراف.",
        "12": "يبتعد عن الأطفال العدوانيين القريبين منه.",
        "13": "يلعب لعباً إيهامياً بسيطاً مع أطفال آخرين.",
        "14": "يلعب مع الآخرين في ألعاب خارجية بدون حساب النتيجة.",
        "15": "يطلب من الآخرين اللعب أو قضاء الوقت معاً.",
        "16": "يلعب مع أطفال آخرين بإشراف محدود.",
        "17": "يتناوب في الألعاب أو الرياضة عندما يُطلب منه ذلك.",
        "18": "يلعب لعباً إيهامياً متقناً مع أطفال آخرين.",
        "19": "يتشارك في الألعاب والممتلكات دون الحاجة لإخباره بذلك.",
        "20": "ينضم إلى مجموعة ترحب به غير لفظياً.",
        "21": "يتناوب في الألعاب أو الرياضة دون أن يُطلب منه ذلك.",
        "22": "يلعب مع الآخرين في ألعاب بسيطة مع حساب النتيجة.",
        "23": "يتبع القواعد في الألعاب أو الرياضة دون إخباره بذلك.",
        "24": "يلعب ألعاب الورق أو ألعاب اللوحة البسيطة القائمة على الحظ.",
        "25": "يبتعد عن مجموعة تُعلن رفضه لفظياً.",
        "26": "يطلب الإذن قبل أخذ أو استخدام أشياء الآخرين.",
        "27": "يُظهر الروح الرياضية في الألعاب أو الرياضة.",
        "28": "يجتمع مع الأقران في منزل أحدهم.",
        "29": "يبتعد عن مجموعة ترفضه بشكل غير لفظي.",
        "30": "يذهب إلى أماكن مع الأقران نهاراً أو ليلاً بإشراف.",
        "31": "يلعب ألعاب اللوح أو الورق أو الإلكترونية التي تتطلب مهارة.",
    },
    "cop": {
        "1": "يسعى إلى الراحة من شخص محبوب عندما يكون مؤلماً أو مضطرباً.",
        "2": "يلجأ إلى والديه أو من يرعاه عندما يقترب منه غريب.",
        "3": "ينفصل بسهولة عن والديه أو من يرعاه.",
        "4": "يتحول بسهولة من نشاط إلى نشاط آخر.",
        "5": "يستجيب بأدب عندما يُعطى شيئاً.",
        "6": "يكون مؤدباً عند طلب شيء.",
        "7": "يتعامل مع التغييرات في الروتين دون انزعاج شديد.",
        "8": "يتعافى بسرعة من خيبة أمل بسيطة.",
        "9": "يستخدم الكلمات أو الإيماءات للتعبير عن الضيق.",
        "10": "يعتذر عن الأخطاء البسيطة غير المقصودة.",
        "11": "يتصرف بشكل مناسب عند تعريفه بأشخاص جدد.",
        "12": "يطلب المساعدة عند الحاجة إليها.",
        "13": "يتصرف بشكل مختلف مع الناس حسب درجة معرفته بهم.",
        "14": "يقبل الاقتراحات والحلول المفيدة من الآخرين.",
        "15": "يعتذر بصدق بعد إيذاء مشاعر الآخرين.",
        "16": "يُقلد سلوك الآخرين في موقف جديد.",
        "17": "يتنازل للتفاهم مع أقرانه.",
        "18": "يتحكم في غضبه عندما تُعطل الأحداث غير المتوقعة خططه.",
        "19": "يلتزم بالحدود الزمنية التي يفرضها والداه أو من يرعاه.",
        "20": "يُدرك أن الناس قد يؤذون الآخرين بغير قصد.",
        "21": "يضبط سلوكه لتجنب إزعاج الآخرين القريبين منه.",
        "22": "يتحكم في غضبه عند عدم الحصول على ما يريد.",
        "23": "يُوفي بوعوده.",
        "24": "يتحكم في غضبه عند تلقي انتقاد بناء.",
        "25": "يُدرك أن الأشخاص الودودين الظاهر قد ينوون الإيذاء.",
        "26": "يحترم وقت الآخرين.",
        "27": "يستخدم الآداب المناسبة دون الحاجة إلى إخباره بذلك.",
        "28": "يُشاهد التلفزيون أو يستمع للراديو للحصول على معلومات.",
        "29": "يذهب إلى بعض الأنشطة المسائية المدرسية عندما يصطحبه أحد الكبار.",
        "30": "يستطيع تقدير عواقب تصرفاته قبل اتخاذ قرارات فيها.",
        "31": "يعتذر عن سلوكه الخاطئ أو أحكامه الخاطئة.",
        "32": "يتذكر المناسبات الخاصة بأفراد عائلته وأصدقائه المقربين.",
        "33": "يبادر بالحوار حول موضوعات لها أهمية خاصة لدى الآخرين.",
        "34": "له هواية من الهوايات.",
        "35": "يُعيد النقود لمن يقوم برعايته والتي إستدانها منه.",
        "36": "يستجيب للتلميحات أو الإشارات غير المباشرة في المحادثة.",
    },
    "gmo": {
        "1": "يُبقي رأسه منتصباً لمدة 15 ثانية على الأقل بدون مساعدة عندما يُحمل في وضع رأسي.",
        "2": "يجلس لمدة دقيقة واحدة على الأقل عن طريق المساعدة.",
        "3": "يلتقط شيئاً صغيراً بيده بأي طريقة ممكنة.",
        "4": "ينقل شيئاً من يد إلى اليد الأخرى.",
        "5": "يلتقط شيئاً بإبهامه وأصابعه.",
        "6": "يرفع نفسه لوضع الجلوس ويبقى دقيقة واحدة على الأقل.",
        "7": "يزحف على الأرض على البطن والركبتين دون أن تلمس يداه الأرض.",
        "8": "يفتح الباب الذي يحتاج للدفع أو السحب.",
        "9": "يُدحرج الكرات عندما يكون جالساً.",
        "10": "يمشي بطريقة بدائية في التجوال.",
        "11": "يقفز داخل وخارج السرير ويستند إلى كرسي الكبار.",
        "12": "يتسلق على جهاز لعب منخفض.",
        "13": "يشخبط بالقلم أو الطباشير على سطح مناسب للكتابة.",
        "14": "يصعد السلالم واضعاً كلتا الرجلين على الدرج.",
        "15": "ينزل السلالم للأمام واضعاً كلتا الرجلين على الدرج.",
        "16": "يجري بسهولة مع تغيير السرعة والاتجاه.",
        "17": "يفتح الباب بواسطة سحب مقبض الباب.",
        "18": "يقفز فوق شيئاً صغير.",
        "19": "يستطيع فتح أو قفل الأدوات التي تحتاج إلى لف.",
        "20": "يُحرك الدراجة أو أي لعبة بثلاث عجلات لمسافة (6) أقدام على الأقل.",
        "21": "يثب على رجل واحدة مرة على الأقل وهو ممسك بشخص آخر أو أي شيء ثابت دون أن يقع.",
        "22": "يبني شكلاً ثلاثي الأبعاد باستخدام خمس مكعبات على الأقل.",
        "23": "يفتح ويقفل المقص بيد واحدة.",
        "24": "ينزل السلالم بتبديل الأرجل دون مساعدة.",
        "25": "يتسلق على جهاز لعب عالٍ أو مرتفع.",
        "26": "يقطع بالعرض ورقة باستخدام المقص.",
        "27": "يثب للأمام على رجل واحدة ثلاث مرات على الأقل دون أن يفقد توازنه.",
        "28": "يُكمل مجموعة مكعبات من ست قطع.",
        "29": "يرسم أكثر من شكل مألوف بالقلم أو بالألوان.",
        "30": "يستخدم المقص في قص خط مرسوم على ورقة.",
        "31": "يستخدم الممحاة دون أن يمزق الورقة.",
        "32": "يقفز للأمام على رجل واحدة بسهولة.",
        "33": "يفتح الأقفال بالمفتاح.",
        "34": "يقص أشياء معقدة بالمقص.",
        "35": "يمسك بكرة تُلقى إليه من بعد عشرة أقدام حتى ولو اقتضى الأمر التحرك لمسكها.",
        "36": "يركب الدراجة دون عجلات التدريب، ودون أن يسقط.",
    },
    "fmo": {
        "1": "يمد يده نحو لعبة أو شيء.",
        "2": "يلتقط الأشياء بإحدى يديه أو بكلتيهما.",
        "3": "ينقل شيئاً من يد إلى اليد الأخرى.",
        "4": "يُخرج شيئاً من صندوق أو حاوية أخرى.",
        "5": "يلتقط أشياء صغيرة بإبهامه وأصابعه.",
        "6": "يلتقط ويُناول لعبة صغيرة أو شيئاً لشخص ما.",
        "7": "يضع شيئاً في صندوق أو حاوية أخرى.",
        "8": "يُشخبط على الورق بقلم تلوين أو قلم أو قلم رصاص.",
        "9": "يفتح الأبواب التي تتطلب دفعها أو سحبها فقط.",
        "10": "يُكدّس أربعة مكعبات على الأقل أو أشياء صغيرة أخرى.",
        "11": "يُقلّب صفحات الكتاب أو المجلة واحدة واحدة.",
        "12": "يفك لف الأشياء الصغيرة.",
        "13": "يفتح الأبواب بتحريك مقبض الباب.",
        "14": "يستخدم حركة لف اليد والمعصم.",
        "15": "يُمسك قلم التلوين/القلم/قلم الرصاص بشكل صحيح للرسم وما شابه ذلك.",
        "16": "يضغط على الأزرار بدقة على لوحة المفاتيح أو الشاشة.",
        "17": "يفتح ويُغلق المقص بيد واحدة.",
        "18": "يرسم دائرة باليد الحرة من مثال.",
        "19": "يُلوّن أشكالاً أو حيوانات بسيطة.",
        "20": "يرسم أكثر من شكل واحد يمكن التعرف عليه.",
        "21": "يسكب السائل من حاوية إلى أخرى.",
        "22": "يرسم مربعاً باليد الحرة من مثال.",
        "23": "يستخدم المقص لقص الورق على خط مستقيم.",
        "24": "يرسم مثلثاً باليد الحرة من مثال.",
        "25": "يستخدم الممحاة دون تمزيق الورق.",
        "26": "يقص أشكالاً بسيطة.",
        "27": "يُلوّن صوراً بسيطة بشكل كامل داخل الخطوط.",
        "28": "يُلوّن مشهداً معقداً باستخدام لونين أو أكثر.",
        "29": "يرسم خطاً مستقيماً باستخدام مسطرة أو مسطرة مستقيمة.",
        "30": "يربط عقدة.",
        "31": "يقص أشكالاً معقدة.",
        "32": "يربط فيونكة محكمة.",
        "33": "يتلاعب بأشياء صغيرة جداً.",
        "34": "يُجمّع/يبني هياكل ألعاب معقدة أو أعمالاً يدوية وما شابه ذلك.",
    },
}

# ═══════════════════════════════════════════════════════════
# MALADAPTIVE BEHAVIOR ITEMS
# ═══════════════════════════════════════════════════════════
MALADAPTIVE_EN = {
    "mal_int": {
        "1": "Is overly needy or dependent.",
        "2": "Has eating problems.",
        "3": "Has sleep problems.",
        "4": "Won't go to/stay at school/work for emotional causes.",
        "5": "Is extremely anxious or nervous.",
        "6": "Cries or is sad for no clear reason.",
        "7": "Avoids interacting with others.",
        "8": "Lacks interest in things that he/she enjoys or used to.",
        "9": "Is extremely fearful of common objects or situations.",
        "10": "Worries for no clear reason.",
        "11": "Is very irritable or moody.",
        "12": "Feels helpless or hopeless.",
        "13": "Complains of feeling sick, etc. with no medical reason.",
    },
    "mal_ext": {
        "1": "Has temper tantrums.",
        "2": "Disobeys those in authority.",
        "3": "Bullies others physically or with words.",
        "4": "Lies, cheats, or steals.",
        "5": "Is physically aggressive.",
        "6": "Is stubborn or argues.",
        "7": "Is verbally abusive.",
        "8": "Breaks rules or laws because of peer pressure.",
        "9": "Is much more active or restless than peers.",
        "10": "Takes school or work property when not allowed.",
        "11": "Destroys his/her or another's possessions on purpose.",
    },
}

MALADAPTIVE_AR = {
    "mal_int": {
        "1": "يمص الإبهام والأصابع.",
        "2": "معتمد على الآخرين بشدة.",
        "3": "ينسحب بعيداً.",
        "4": "يبلل الفراش.",
        "5": "يعاني من اضطراباً في الأكل.",
        "6": "يعاني من اضطراباً في النوم.",
        "7": "يقلم أظافره.",
        "8": "يتجنب الذهاب إلى المدرسة.",
        "9": "يُبدي قلقاً بالغاً.",
        "10": "لديه لازمة (حركات وتقلصات لارادية).",
        "11": "يضحك أو يبكي بسهولة بالغة.",
        "12": "يملك قدرة ضعيفة على تركيز نظره إتجاه شيء محدد.",
        "13": "يعاني من كآبه شديدة.",
    },
    "mal_ext": {
        "1": "يبدي عدم الاحترام والتقدير.",
        "2": "يكذب أو يغش أو يسرق.",
        "3": "يميل بشدة إلى الاعتداء البدني.",
        "4": "يحلف في مواقف غير مناسبة.",
        "5": "يهرب.",
        "6": "عنيد أو كنيب.",
        "7": "يتهرب من المدرسة أو العمل.",
        "8": "غير واعٍ لما يحدث حوله.",
        "9": "يهتز للأمام وإلى الخلف عندما يكون جالساً أو واقفاً.",
        "10": "يبدي عدم الاحترام والتقدير.",
        "11": "يكذب أو يغش أو يسرق.",
    },
}

# ═══════════════════════════════════════════════════════════
# CRITICAL ITEMS
# ═══════════════════════════════════════════════════════════
CRITICAL_ITEMS_EN = {
    "1": "Gets fixated on objects or parts of objects.",
    "2": "Hears voices or sees things that others do not.",
    "3": "Harms himself/herself.",
    "4": "Uses strange or repetitive speech.",
    "5": "Loses awareness of what is happening around him/her.",
    "6": "Repeats physical movements over and over.",
    "7": "Has toileting accidents.",
    "8": "Eats non-food items such as dirt, paste, or soap.",
    "9": "Engages in compulsive behavior.",
    "10": "Shows excessive interest in weapons or violence.",
    "11": "Harms animals.",
    "12": "Has delusional beliefs.",
    "13": "Gets so fixated on a topic that it annoys others.",
    "14": "Talks about killing himself/herself or has tried to.",
    "15": "Has no response to pain.",
    "16": "Wanders or darts away without regard for safety.",
    "17": "Threatens to hurt or kill someone.",
    "18": "Is tricked into doing something that could cause harm.",
    "19": "Gets fixated on a person in a way that is unwanted.",
    "20": "Engages in unwanted sexual behavior.",
}

CRITICAL_ITEMS_AR = {
    "1": "لديه إصرار على الأشياء أو أجزاء منها.",
    "2": "يسمع أصواتاً أو يرى أشياء لا يراها الآخرون.",
    "3": "يُؤذي نفسه.",
    "4": "يستخدم كلاماً غريباً أو متكرراً.",
    "5": "يفقد الوعي بما يحدث حوله.",
    "6": "يُكرر حركات جسدية مراراً وتكراراً.",
    "7": "لديه حوادث تبول أو تبرز غير إرادية.",
    "8": "يأكل أشياء غير غذائية كالتراب أو الصمغ أو الصابون.",
    "9": "يمارس سلوكاً قهرياً.",
    "10": "يُظهر اهتماماً مفرطاً بالأسلحة أو العنف.",
    "11": "يُؤذي الحيوانات.",
    "12": "لديه معتقدات وهمية.",
    "13": "يتشبث بموضوع ما بصورة تُزعج الآخرين.",
    "14": "يتحدث عن قتل نفسه أو حاول ذلك.",
    "15": "لا يستجيب للألم.",
    "16": "يتجول أو يبتعد بلا اعتبار للسلامة.",
    "17": "يُهدد بإيذاء أو قتل شخص ما.",
    "18": "يُخدع للقيام بشيء قد يُسبب ضرراً.",
    "19": "يتشبث بشخص بطريقة غير مرغوب فيها.",
    "20": "يمارس سلوكاً جنسياً غير مرغوب فيه.",
}
